export const SET_DATA_FORM = 'SET_DATA_FORM'
export const EMPTY_FORM = 'EMPTY_FORM'
export const SAVE_FORM_REQUEST = 'SAVE_FORM_REQUEST'
export const SAVE_FORM_SUCCESS = 'SAVE_FORM_SUCCESS'
export const SAVE_FORM_FAIL = 'SAVE_FORM_FAIL'

export const FETCH_REGISTRIES_REQUEST = 'FETCH_REGISTRIES_REQUEST'
export const FETCH_REGISTRIES_SUCCESS = 'FETCH_REGISTRIES_SUCCESS'
export const FETCH_REGISTRIES_FAIL = 'FETCH_REGISTRIES_FAIL'
